from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from training.monitoring import (
    SWANLAB_RUN_ID_FILE,
    SwanLabScalarLogger,
    checkpoint_step_from_path,
    configure_swanlab_environment,
    normalize_swanlab_mode,
    normalize_swanlab_resume,
    replay_swanlab_history,
    require_swanlab,
    resolve_swanlab_run_id,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay local training metrics history to a SwanLab run.")
    parser.add_argument("--output-dir", required=True, help="Training output directory.")
    parser.add_argument("--metrics-path", help="Optional metrics JSONL path. Defaults to output-dir metrics files.")
    parser.add_argument("--checkpoint", help="Checkpoint directory used to infer replay upper step.")
    parser.add_argument("--max-step", type=int, help="Only replay metrics with step <= max-step.")
    parser.add_argument("--swanlab-project", default="agentic-rag-rl")
    parser.add_argument("--swanlab-workspace")
    parser.add_argument("--swanlab-mode", default="cloud", choices=["cloud", "local", "offline", "disabled"])
    parser.add_argument("--swanlab-logdir", default=str(ROOT / "training" / "swanlab"))
    parser.add_argument("--swanlab-experiment-name")
    parser.add_argument("--swanlab-run-id", help="Explicit SwanLab run id. If omitted, output-dir/swanlab_run_id.txt is used.")
    parser.add_argument("--swanlab-resume", default="allow", choices=["allow", "must", "never"])
    parser.add_argument("--dry-run", action="store_true", help="Print replay summary without uploading to SwanLab.")
    return parser.parse_args()


def project_path(value: str | Path) -> Path:
    path = Path(value)
    if not path.is_absolute():
        path = ROOT / path
    return path


def infer_max_step(output_dir: Path, checkpoint: Path | None, explicit_max_step: int | None) -> int | None:
    if explicit_max_step is not None:
        return explicit_max_step
    if checkpoint is not None:
        return checkpoint_step_from_path(checkpoint)
    checkpoints: list[tuple[int, Path]] = []
    for path in output_dir.glob("checkpoint-*"):
        step = checkpoint_step_from_path(path)
        if step is not None:
            checkpoints.append((step, path))
    if not checkpoints:
        return None
    return sorted(checkpoints, key=lambda item: item[0])[-1][0]


def dry_run_swanlab_run_id(output_dir: Path, explicit_run_id: str | None) -> str:
    if explicit_run_id:
        return explicit_run_id
    state_path = output_dir / SWANLAB_RUN_ID_FILE
    if state_path.exists():
        run_id = state_path.read_text(encoding="utf-8").strip()
        if run_id:
            return run_id
    return "<auto-generated-on-run>"


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")

    args = parse_args()
    output_dir = project_path(args.output_dir)
    metrics_path = project_path(args.metrics_path) if args.metrics_path else None
    checkpoint = project_path(args.checkpoint) if args.checkpoint else None
    max_step = infer_max_step(output_dir, checkpoint, args.max_step)

    if args.dry_run:
        run_id = dry_run_swanlab_run_id(output_dir, args.swanlab_run_id)
        summary = replay_swanlab_history(
            SimpleNamespace(log=lambda payload, step: None),
            output_dir,
            run_id=run_id,
            max_step=max_step,
            metrics_path=metrics_path,
            checkpoint_path=checkpoint,
            dry_run=True,
        )
        print(
            json.dumps(
                summary,
                ensure_ascii=False,
                indent=2,
            )
        )
        return

    run_id = resolve_swanlab_run_id(output_dir, explicit_run_id=args.swanlab_run_id)
    mode = normalize_swanlab_mode(args.swanlab_mode) or "cloud"
    resume = normalize_swanlab_resume(args.swanlab_resume) or "allow"
    configure_swanlab_environment(
        project=args.swanlab_project,
        workspace=args.swanlab_workspace,
        mode=mode,
        logdir=project_path(args.swanlab_logdir),
        experiment_name=args.swanlab_experiment_name or output_dir.name,
        run_id=run_id,
        resume=resume,
    )
    require_swanlab(["swanlab"])
    logger = SwanLabScalarLogger(
        project=args.swanlab_project,
        workspace=args.swanlab_workspace,
        experiment_name=args.swanlab_experiment_name or output_dir.name,
        mode=mode,
        logdir=project_path(args.swanlab_logdir),
        config={"history_replay": True, "output_dir": str(output_dir), "max_step": max_step},
        run_id=run_id,
        resume=resume,
    )
    try:
        summary = logger.replay_history(
            output_dir,
            max_step=max_step,
            metrics_path=metrics_path,
            checkpoint_path=checkpoint,
        )
    finally:
        logger.finish()
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
